---
# ------------------------- #
# Input Files Customization #
# ------------------------- #

#input files template
TEMPLS:
  WF: qce_wf.tmpl
  DISP: qce_disp.tmpl

#Number of processors for parallel jobs
PROC: 4

# ------------------ #
# Directory location #
# ------------------ #

#Directory containing the source databases to replicate
DATABASES_DIR: Databases

#Directory containing all xyz files (full or relative path)
GEOMETRIES_DIR: Geometries

#Where intermediate wavefunctions are stored for a given DFT, basis, and method
WAVEFUNCTIONS_DIR: Wavefunctions

#Where raw output energies are stored for a given dispersion, DFT, basis, and method
DISPERSION_DIR: Dispersion

#Directory where the output file structures is created (full or relative path)
OUTPUTS_DIR: Outputs

# ------------------ #
# Databases to Build #
# ------------------ #

# With each database, a list of DFTs to evaluate is provided
DATABASES:
  test_water:
    dfts: # Here, we list out our DFTs...
      # Dict of dft name -> dispersion corrections
      # Use `null` for no dispersion
      B3LYP: [null, "D2", "D3", "D3ZERO"]
      PBE0: [null, "D2", "D3", "D3ZERO"]
      # Note that VV10 dispersion (or rVV10, for that matter) CANNOT be added to the dispersion list!
      # The behavior is undefined if you do...
      # You MUST define it as its own SCF calculation:
      # wB97x-V: [null]

# ------------------- #
# Calculation Methods #
# ------------------- #

# Calculation methods; Basis and spherical points
# This is a dictionary of name -> options. Options are passed as template args right to your .tmpl file.
METHODS:
  def2-QZVPPD_99x590:
    basis: def2-QZVPPD
    reference: UHF
    spherical_points: 590
    radial_points: 99
  def2-QZVPPD_500x974:
    basis: def2-QZVPPD
    reference: UHF
    spherical_points: 974
    radial_points: 500

#Rules to set the method used by a particular dataset
#Rules are evaluated in order. Once a rule is matched, evaluation stops. For a rule to match, the given attribute must
#exactly match each field, or if an array is provided, one of the values in the array.
#You can match based on the following:
# - DATABASE - The database that is being built... I.e, the parent directory of the `IndValues.csv` file
# - DATASET - The dataset within the database. I.e, everything before the last `_` in the datapoint name
# - POINT - Individual datapoints
RULES:
  - match:
      DATABASE: test_water
    method: def2-QZVPPD_99x590
    units: { INP_DATASETEVAL: 1.0 }
  - match:
      DATASET: ['AE18', 'RG10']
      DATABASE: MGCDB84
    method: def2-QZVPPD_500x974
    units: { INP_DATASETEVAL: 1.0 }
  - match:
      DATABASE: MGCDB84
    method: def2-QZVPPD_99x590
    units: { INP_DATASETEVAL: 1.0 }

# ---------------- #
# Running the jobs #
# ---------------- #

#Call to the quantum chemistry program
QCENGINE_CALL: "psi4 -n {nproc} {input} {output.rawout}"   # Psi4
          # "g16 {input} {output}"                 #Gaussian

REGEXPS:
  #regexp to extract final energies from output files
  ENERGY: '    Total Energy =\s*' # Psi4
        # 'SCF Done:  E({method}) =  '                # Gaussian
  DISP: 'Computed Dispersion Energy:\s*'
  TIME: '\s*Psi4 wall time for execution:\s*(?P<hours>[0-9]+):(?P<minutes>[0-9]+):(?P<seconds>[0-9\.]+)'

# A method for dealing with the different units being thrown around everywhere
# Energy of 1 Hartree in the designated unit. For Psi4, this is 1.0 since it outputs in Hartrees.
# If your software outputs in eV, for example, this would be 27.211396641308 Hartrees/eV
# Find this in the first ROW of https://ryutok.github.io/EnergyConversionTable/
UNITS:
  # Energy scaling factor for the output of your program
  INP_QCENGINE: 1.0 # Psi4 1.0 Hartree/Hartree
  # Energy scaling factor for the study's reference values stored in DatasetEval.csv
  INP_DATASETEVAL: null # Set per-database above.
  
  # Energy scaling factor for what YOU want IndValues.csv to be in
  # Be aware that this must be set correctly to directly reproduce the values of studies!
  OUT_INDVALUES: 627.509 # Units switch once again: 627.509 Hartrees/kcal/mol

...
