---
# ------------------------- #
# Input Files Customization #
# ------------------------- #

#input files template filename -- See psi4.tmpl for an example
TEMPL1: qcengine.tmpl

#Number of processors for parallel jobs
PROC: 4

# ------------------ #
# Directory location #
# ------------------ #

#Directory containing the source databases to replicate
DATABASES_DIR: Databases

#Directory containing all xyz files (full or relative path)
GEOMETRIES_DIR: Geometries

#Where raw output energies are stored for a given DFT, basis, and method
ENERGIES_DIR: Energies

#Directory where the output file structures is created (full or relative path)
OUTPUTS_DIR: Outputs

# ------------------ #
# Databases to Build #
# ------------------ #

# With each database, a list of DFTs to evaluate is provided
DATABASES:
  test_water:
    dfts: ["B3LYP", "PBE0"]

# ------------------- #
# Calculation Methods #
# ------------------- #

# Calculation methods; Basis and spherical points
# This is a dictionary of name -> options. Options are passed as template args right to your .tmpl file.
METHODS:
  def2-QZVPPD_99x590:
    basis: def2-QZVPPD
    reference: UHF
    spherical_points: 590
    radial_points: 99
  def2-QZVPPD_500x974:
    basis: def2-QZVPPD
    reference: UHF
    spherical_points: 974
    radial_points: 500

#Rules to set the method used by a particular dataset
#Rules are evaluated in order. Once a rule is matched, evaluation stops. For a rule to match, the given attribute must
#exactly match each field, or if an array is provided, one of the values in the array.
#You can match based on the following:
# - DATABASE - The database that is being built... I.e, the parent directory of the `IndValues.csv` file
# - DATASET - The dataset within the database. I.e, everything before the last `_` in the datapoint name
# - POINT - Individual datapoints
RULES:
  - match:
      DATABASE: test_water # This rule matches the `test_water` database
    method: def2-QZVPPD_99x590 # ...and sets the method to use a def2-QZVPPD basis set and others as defined above
    # Override the energy scaling factor to get the right units... This study stores reference values in Hartree
    # ... but the output is in kcal/mol... see the `UNITS` field below
    units: { INP_DATASETEVAL: 1.0 }
  - match:
      DATASET: ['AE18', 'RG10'] # Here, we match specific datasets -- The source study defines a different grid for these
      DATABASE: MGCDB84
    method: def2-QZVPPD_500x974
    units: { INP_DATASETEVAL: 1.0 }
  - match:
      DATABASE: MGCDB84 # Note that the rule for the main database is placed after the more specific one as a "catch all"
    method: def2-QZVPPD_99x590
    units: { INP_DATASETEVAL: 1.0 }

# ---------------- #
# Running the jobs #
# ---------------- #

#Call to the quantum chemistry program
QCENGINE_CALL: "psi4 -n {nproc} {input} {output}"   # Psi4
          # "g16 {input} {output}"                 #Gaussian

#regexp to extract final energies from output files
REGEXP: '    Total Energy =\s*' # Psi4
      # 'SCF Done:  E({method}) =  '                # Gaussian

#regexp to extract the runtime from output files
#Can be tested with something like https://regex101.com/; Beware, group naming syntax is not standard; Use the Python
#  standard for naming groups: (?P<name>...) instead of (?<name>...)
#Valid group names are days, hours, minutes, seconds, millis (self-explanatory)
TIME_REGEXP: '\s*Psi4 wall time for execution:\s*(?P<hours>[0-9]+):(?P<minutes>[0-9]+):(?P<seconds>[0-9\.]+)'

# A method for dealing with the different units being thrown around everywhere
# Energy of 1 Hartree in the designated unit. For Psi4, this is 1.0 since it outputs in Hartrees.
# If your software outputs in eV, for example, this would be 27.211396641308 Hartrees/eV
# Find this in the first ROW of https://ryutok.github.io/EnergyConversionTable/
UNITS:
  # Energy scaling factor for the output of your program
  INP_QCENGINE: 1.0 # Psi4 1.0 Hartree/Hartree
  # Energy scaling factor for the study's reference values stored in DatasetEval.csv
  INP_DATASETEVAL: null # Set per-database above.
  
  # Energy scaling factor for what YOU want IndValues.csv to be in
  # Be aware that this must be set correctly to directly reproduce the values of studies!
  OUT_INDVALUES: 627.509 # Units switch once again: 627.509 Hartrees/kcal/mol

...
